Fixes #5. No tests added yet
tingvarsson/telegram.ongabot pull request #20
Opened 2021-03-12 10:13 UTC by walkerjens

2021-03-12 12:18 UTC, walkerjens commented
Also fixes #6 in addition to #5

2021-03-12 13:00 UTC, tingvarsson requested changes

2021-03-13 21:53 UTC, walkerjens commented on ongabot/handler/canceleventcommand.py
> +            + get_upcoming_wednesday_date(date.today()).strftime("%Y-%m-%d")
Changed message to contain date from poll.

2021-03-13 21:58 UTC, walkerjens commented on ongabot/handler/neweventcommand.py
> +        if next_wed.strftime("%Y-%m-%d") in pinned_poll.poll.question:
We still need to match the date stored with upcoming wednesday date. In this manner we keep the original data structure (message) intact which obfuscates less than a custom data structure. I vote that this way remains, at least until any further benefit from a custom struct is evident.

2021-03-14 10:43 UTC, tingvarsson commented on ongabot/handler/neweventcommand.py
> +        if next_wed.strftime("%Y-%m-%d") in pinned_poll.poll.question:
aight.

2021-03-14 10:46 UTC, tingvarsson approved these changes

2021-03-14 10:50 UTC, merged